### ISSUE TITLE
Can't deploy to Heroku

### ISSUE THREAD

**Issue by lowellbander** [facebookarchive/hack-example-site#17]
I've cloned this repo, added the Procfile, and pushed to Heroku. When I view the Heroku logs, it says the app as crashed and that the ``hhvm`` command was not found, even though the stack is cedar-14. Help?

**Comment by jwatzman** [comment]
Are you able to deploy any HHVM app at all, e.g., even a hello world app? That sounds like a Heroku issue

**Comment by lowellbander** [comment]
I'm enough of a noob to think that this was a hello world app. I'm just
getting started with Hack/HHVM and have tried a couple tutorials to get
started, but haven't been able to get off the ground. (Interning at fb this
summer and wanted to get some exposure before I start.)

**Comment by jwatzman** [comment]
It seems quite likely that Heroku changed their setup since the directions were written. If you figure it out, would love a PR to fix it :)

For getting started, I'd look at https://github.com/facebook/hhvm/wiki/Getting-Started -- it's pretty simple on Ubuntu 14.04. A couple commands to install the HHVM repo, then HHVM and nginx, and a script will set up nginx for you.

**Comment by mauriciord** [comment]
I'am doing exactly what is on README, but didn't work for me.

**Comment by JoelMarcey** [comment]
This repo has been deprecated and archived.
